kartMotos/apps/usuarios/urls.py
#
from django.contrib import admin
from django.urls import path
from . import views

app_name="usuarios"

urlpatterns = [

	#path('Modificar/<str:pk>', views.Modificar.as_view(), name="modificar"),

    path('RegistrarUsuario/',views.RegistroUsuario.as_view(), name = "registrar_usuario"),

]

kartMotos/kartMotos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home,name='home'),
   	path('contacto',views.contacto,name='contacto'),
    path('nosotros',views.nosotros, name='nosotros'),
    path('cuidados',views.cuidados, name='cuidados'),
    path('Login',auth.LoginView.as_view(template_name="usuarios/login.html"),name="login"),
    path('Logout',auth.LogoutView.as_view(),name="logout"),

    #Url de las apps
    path('usuarios/',include('apps.usuarios.urls')),
    path('carreraKarting/',include('apps.carreraKarting.urls')),
    path('pilotokart/',include('apps.pilotokart.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kartMotos/apps/pilotokart/models.py
from django.db import models
from apps.carreraKarting.models import CarreraKarting


# Create your models here.

class PilotoKart(models.Model):
    
    OpcionCategoria = [
		('1', '125cc'),
        ('2', '150cc'),
        ('3', '300cc'),
        ('4', '350cc'),
        ('5', '400cc'),
        ('6', '500cc'),
        ('7', '700cc'),
        ('8', '710cc'),
        ('9', '800cc'),
    ]
    
    nombre = models.CharField(max_length = 50)
    apellido = models.CharField(max_length = 50)
    dni = models.BigIntegerField()
    fecha_nacimiento = models.DateField('Fecha de Nacimiento(DD/MM/AAAA)',null=True)
    domicilio = models.CharField(max_length = 50)
    ciudad = models.CharField(max_length = 50)
    provincia = models.CharField(max_length = 50)
    email = models.EmailField()
    telefono = models.BigIntegerField(null = True,blank=True)
    numero_kart = models.BigIntegerField()
    categoria = models.CharField(max_length=1,choices= OpcionCategoria)
    carrera = models.ForeignKey(CarreraKarting, null=True, related_name = 'piloto_carrera', on_delete = models.SET_NULL)
    #fecha_inscripcion = models.DateField()

kartMotos/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
	#DNI = models.PositiveIntegerField(serialize = False, verbose_name = 'DNI', null=True)
#	fecha_nacimiento = models.DateField('Fecha de Nacimiento(DD/MM/AAAA)',null=True)
	username = models.CharField(max_length = 50, null=True, blank=True)
	email = models.EmailField('Email', unique=True)
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']
	is_admin = models.BooleanField(default=False,null=False, blank=True)
	
	def __str__(self):
		return self.first_name + self.last_name

	
	
	

kartMotos/apps/usuarios/forms.py
#
from django import forms
from .models import Usuario
from django.db import transaction
from django.contrib.auth.forms import UserCreationForm

""" 

class ModificarUsuario(forms.ModelForm):

	class Meta:
		model = Usuario
		fields = ['first_name','last_name','email','fecha_nacimiento'] """



class UsuarioForm(UserCreationForm):


	class Meta:
		model = Usuario 
		fields = ['first_name','last_name','email','password1','password2']
""" 
	@transaction.atomic
	def save(self):
		usuario = super().save(commit = False)
		usuario.save()
		Usuario.objects.create(usuario=usuario)
		return usuario """

kartMotos/apps/usuarios/views.py
#
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
#from .forms import ModificarUsuario
from .models import Usuario
from django.shortcuts import render
from .forms import UsuarioForm
from django.views.generic import CreateView

""" 
class Modificar(UpdateView):
	model = Usuario
	form_class = ModificarUsuario
	template_name = 'usuarios/modificarUsuario.html'
	success_url = reverse_lazy('home') """


# Create your views here.
class RegistroUsuario(CreateView):
	model = Usuario
	form_class = UsuarioForm
	template_name = 'usuarios/registro_usuario.html'
	success_url = reverse_lazy('home')

kartMotos/templates/usuarios/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block contenido %}
<div class="container d-flex flex-column bg-white mt-5" style="width: 400px; border-radius: 25px;">
	<div class="row align-self-center text-center mt-3">
		<div class="col-12">
			<h1>Iniciar Sesión</h1>
		</div>
	</div>
	<div class="row align-self-center text-center mt-2">
		<div class="col-12">
			<h6>Por favor, ingresá tu correo y contraseña</h6>
		</div>

	</div>
	<div class="row align-self-center text-center mt-4 mb-5">
		<div class="col-12">
			<form method="POST">{%csrf_token%}
				{{form.errors}}
				<div class="form-group">
					<label for="id_username">Correo electrónico</label>
					<input type="email" name="username" autofocus="" autocapitalize="none" autocomplete="username"
						maxlength="254" required="" class="form-control" id="id_username" aria-describedby="emailHelp"
						placeholder="Ingrese su email">
				</div>
				<div class="form-group">
					<label for="id_password">Contraseña</label>
					<input type="password" name="password" required="" class="form-control" id="id_password"
						placeholder="Contraseña">
				</div>
				<button type="submit" class="btn btn-danger btn-lg font-weight-bold align-self-center text-center mt-3"
					style="border-radius: 25px; width: 200px; font-size: 14px;">INGRESAR</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

kartMotos/templates/usuarios/modificarUsuario.html
{% extends 'base.html' %}

{% block contenido %}


<section class="container">

	<div class="row mt - justify-content-center">
		<h1 class="nuevaLetra mb-5 mt-5 justify-content-center text-white font-weight-bolder text-uppercase">Modificar
			datos cliente</h1>
		{{form.errors}}
		<div class="col-10 bg-white p-5">

			<form method="POST">{% csrf_token %}
				<div id="div_id_first_name" class="form-group row">

					<label for="id_first_name" class="col-sm-4 col-form-label"><strong>Nombre</strong></label>
					<div class="col-sm-4">
						<input type="text" name="first_name" value="" maxlength="30"
							class="form-control bg-light text-dark" id="id_first_name"
							placeholder="Introduzca un nuevo nombre">
					</div>
				</div>

				<div id="div_id_last_name" class="form-group row">
					<label for="id_last_name" class="col-sm-4 col-form-label"><strong>Apellido</strong></label>
					<div class="col-sm-4">
						<input type="text" name="last_name" value="" maxlength="150"
							class="form-control bg-light text-dark" id="id_last_name"
							placeholder="Introduzca un nuevo apellido">
					</div>
				</div>

				<div id="div_id_email" class="form-group row">
					<label for="id_email" class="col-sm-4 col-form-label"><strong>Correo Electrónico</strong><span
							class="asteriskField">*</span></label>
					<div class="col-sm-4">
						<input type="email" name="email" value="" maxlength="254"
							class="form-control bg-light text-dark" required="" id="id_email"
							placeholder="Nuevo correo electrónico">
					</div>
				</div>
				<div id="div_id_fecha_nacimiento" class="form-group row">
					<label for="id_fecha_nacimiento" class="col-sm-4 col-form-label">
						<strong>Fecha de Nacimiento(DD/MM/AAAA)</strong><span class="asteriskField">*</span></label>
					<div class="col-sm-4 ">
						<input type="text" name="fecha_nacimiento" value="" class="form-control bg-light text-dark"
							required="" id="id_fecha_nacimiento" placeholder="Nueva fecha de nacimiento">
					</div>
				</div>


				<div class="div.col align-self-center text-center">

					<button type="submit" class="btn btn-danger btn-sm font-weight-bold align-self-center text-center"
						style="border-radius: 40px;">Enviar</button>

				</div>


			</form>
		</div>
	</div>
</section>

{% endblock %}

kartMotos/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block contenido %}
<h1>¡Registrarse acá!</h1>
{{form.errors}}
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
	{{ form|crispy }}

	<input type="submit" value="Crear">
</form>

{% endblock%}

kartMotos/templates/usuarios/registro_cliente.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block contenido %}
<h1>¡Registrarse acá!</h1>
{{form.errors}}
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
	{{ form|crispy }}

	<input type="submit" value="Crear">
</form>

{% endblock%}

kartMotos/templates/usuarios/registro_usuario.html
{% extends 'base.html' %}

{% load static %}



{% block contenido %}
{{form.errors}}
<div class="container justify-content-center">
    <h1 class="text-center text-light pt-3 font-weight-bold">Registrarse</h1>
</div>

<div class="container bg-white d-flex justify-content-center mt-5 align-middle  align-items-center"
    style="width: 75%; border-radius: 25px;">
    <form action="" method="post" enctype="multipart/form-data" style="width: 90%">{% csrf_token %}

        <div class="form-group row mt-5">
            <div class="form-group col-4 text-right font-weight-bold">
                <label for="id_email" class="col-form-label"><span class="asteriskField">*</span>Correo
                    electrónico:</label>
            </div>
            <div class="form-group col-8">
                <input type="email" name="email" maxlength="254" autofocus="" class="emailinput form-control"
                    required="" id="id_email">
            </div>
        </div>

        <div class="form-group row">
            <div class="form-group col-4 text-right font-weight-bold">
                <label for="id_first_name" class="col-form-label">Nombre:</label>
            </div>
            <div class="form-group col-8">
                <input type="text" name="first_name" maxlength="30" class="textinput textInput form-control"
                    id="id_first_name">
            </div>
        </div>

        <div class="form-group row">
            <div class="form-group col-4 text-right font-weight-bold">
                <label for="div_id_last_name" class="col-form-label">Apellido:</label>
            </div>
            <div class="form-group col-8">
                <input type="text" name="last_name" maxlength="150" class="textinput textInput form-control"
                    id="id_last_name">
            </div>
        </div>

        <div class="form-group row">
            <div class="form-group col-4 text-right font-weight-bold">
                <label for="id_password1" class="col-form-label"><span class="asteriskField">*</span>Contraseña:</label>
            </div>
            <div class="form-group col-8">
                <input type="password" name="password1" autocomplete="new-password"
                    class="textinput textInput form-control" required="" id="id_password1">
                <div id="hint_id_password1" class="help-block">
                    <ul>
                        <li>Su contraseña no puede ser similar a otros componentes de su información personal.</li>
                        <li>Su contraseña debe contener por lo menos 8 caracteres.</li>
                        <li>Su contraseña no puede ser una contraseña usada muy comúnmente.</li>
                        <li>Su contraseña no puede estar formada exclusivamente por números.</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="form-group col-4 text-right font-weight-bold">
                <label for="id_password2" class="col-form-label"><span class="asteriskField">*</span>Confirmación de
                    contraseña:</label>
            </div>
            <div class="form-group col-8">
                <input type="password" name="password2" autocomplete="new-password"
                    class="textinput textInput form-control" required="" id="id_password2">
                <div id="hint_id_password2" class="help-block">Introduzca la misma contraseña nuevamente, para poder
                    verificar la misma.</div>
            </div>
        </div>
<!-- 
        <div class="form-group row">
            <div class="form-group col-4 text-right font-weight-bold">
                <label for="id_DNI" class="col-form-label"><span class="asteriskField">*</span>DNI:</label>
            </div>
            <div class="form-group col-8">
                <input type="number" name="DNI" min="0" class="numberinput form-control" required="" id="id_DNI">
            </div>
        </div> -->

        <div class="container d-flex justify-content-center mx-auto d-flex align-items-center mt-3">
            <input type="submit" value="Registrarse"
                class="bg-danger pl-3 pr-3 pt-2 pb-2 border-0 text-white font-weight-bold mr-2"
                style="border-radius: 50px;">
        </div>
    </form>
</div>


{% endblock%}