kartMotos/apps/carreraKarting/urls.py
from django.urls import path
from . import views

app_name = 'carrera_karting'

urlpatterns = [
    path('registrarCarreraKarting/',views.RegistrarCarreraKarting.as_view(), name = "registrar_carrera"),
    
]

kartMotos/apps/pilotokart/urls.py
from django.urls import path
from . import views

app_name = 'pilotokart'

urlpatterns = [
    path('registrarPilotoKart/',views.RegistrarPilotoKart.as_view(), name = "registrar_piloto_kart"),
    path('listarPilotoKart/',views.ListarInscripciones, name = "listar_piloto_kart"),
]

kartMotos/apps/usuarios/urls.py
#
from django.contrib import admin
from django.urls import path
from . import views

app_name="usuarios"

urlpatterns = [

	#path('Modificar/<str:pk>', views.Modificar.as_view(), name="modificar"),

    path('RegistrarUsuario/',views.RegistroUsuario.as_view(), name = "registrar_usuario"),

]

kartMotos/kartMotos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home,name='home'),
   	path('contacto',views.contacto,name='contacto'),
    path('nosotros',views.nosotros, name='nosotros'),
    path('cuidados',views.cuidados, name='cuidados'),
    path('Login',auth.LoginView.as_view(template_name="usuarios/login.html"),name="login"),
    path('Logout',auth.LogoutView.as_view(),name="logout"),

    #Url de las apps
    path('usuarios/',include('apps.usuarios.urls')),
    path('carreraKarting/',include('apps.carreraKarting.urls')),
    path('pilotokart/',include('apps.pilotokart.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kartMotos/kartMotos/forms.py
from django import forms

class FormularioContacto(forms.Form):

	asunto = forms.CharField(max_length=100)
	nombre = forms.CharField(max_length=100)
	email = forms.EmailField(required=False, label='Tu correo electronico')
	mensaje = forms.CharField(widget=forms.Textarea)

	def clean_mensaje(self):
		mensaje = self.cleaned_data['mensaje']
		num_palabras = len(mensaje.split())
		if num_palabras < 4:
			raise forms.ValidationError("¡Se requieren mínimo 4 palabras!")
		return mensaje

kartMotos/templates/base.html
<!DOCTYPE html>
<html>

<head>
	<title>Turnos</title>
	<!-- Boostrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
		integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!-- Styles CSS -->
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<!-- Scripts -->
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>


	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<script src="https://kit.fontawesome.com/28abe86f4b.js" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
</head>

<body>

	<!-- NAVBAR -->
	<div class="container-fluid bg-light fixed-top border-white" style="border-style: none none solid none;">
		<div class="header row">
			<div class="col-4 d-flex justify-content-center">
				<a class="navbar-brand mt-2" href="{% url 'home' %}">Carreras</a>
			</div>

			<div class="col-4 d-flex justify-content-center">
				<nav class="navbar navbar-expand-sm">
					<ul class="navbar-nav" style="font-size: 20px;">
						<li class="nav-item pl-5 pr-5"><a href="{% url 'nosotros' %}">Nosotros</a></li>
						<li class="nav-item pl-5 pr-5"><a href="{% url 'contacto' %}">Contacto</a></li>
						<!-- <li class="nav-item pl-5 pr-5"><a href="{% url 'cuidados' %}">Cuidados</a></li> -->
					</ul>
				</nav>
			</div>
			<!-- Dropdown -->
			<div class="col-4 d-flex justify-content-center">
				{% if user.is_authenticated %}
				<nav class="navbar navbar-expand-sm">
					<ul class="navbar-nav" style="font-size: 18px;">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle bg-light text-dark pl-3 pr-3" href="#" id="navbardrop"
								data-toggle="dropdown" style="border-radius: 20px;">
								{{user.first_name}}
							</a>
							<div class="dropdown-menu">
								{% if user.es_admin == 0 %}
								<a class="dropdown-item" href="{% url 'usuarios:modificar' user.DNI %}">Modificar
									Cliente</a>
								<a class="dropdown-item"
									href="{% url 'autoevaluacion:crearFuncion'%}">Autoevaluacion</a>
								<a class="dropdown-item" href="{% url 'autoevaluacion:listar' %}">Resultado
									Autoevaluación</a>
								{% endif %}

								<form action="{% url 'logout' %}">
									<button type="submit"
										class="btn btn-light btn-sm align-self-center text-center">Cerrar
										sesión</button>
								</form>
							</div>
						</li>
					</ul>
				</nav>

				{% endif %}
			</div>
		</div>
	</div>

	<!-- Bloques -->
	<div class="container-fluid mt-5 pt-4">
		{% block contenido %}

		{% endblock %}
	</div>
</body>

</html>

kartMotos/templates/contacto.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block contenido %}


<html>

<head>
	<title>Contactanos</title>
</head>

<body>

	<section class="container">
		<div class="row mb-5 justify-content-center">
			<h1 class="mb-5 mt-5 justify-content-center text-white font-weight-bolder text-uppercase">Contactanos</h1>
			{% if form.errors %}

			<p style="color: red;">Por favor corrige lo siguiente:</p>

			{% endif %}
			<div class="col-10 bg-white p-5">

				<form method="POST">{% csrf_token %}
					<div id="div_id_asunto" class="form-group row">

						<label for="id_asunto" class="col-sm-4 col-form-label requiredField"><strong>Asunto</strong>
							<span class="asteriskField">*</span></label>
						<div class="col-sm-4">
							<input type="text" name="asunto" value="" maxlength="100"
								class="form-control bg-light text-dark" id="id_asunto"
								placeholder="Ingrese el motivo del contacto">
						</div>
					</div>

					<div id="div_id_nombre" class="form-group row">

						<label for="id_nombre" class="col-sm-4 col-form-label requiredField"><strong>Nombre y
								Apellido</strong> <span class="asteriskField">*</span></label>
						<div class="col-sm-4">
							<input type="text" name="nombre" value="" maxlength="100"
								class="form-control bg-light text-dark" id="id_nombre"
								placeholder="Ingrese nombre y apellido">
						</div>
					</div>

					<div id="div_id_email" class="form-group row">
						<label for="id_email" class="col-sm-4 col-form-label"><strong>Tu correo
								electronico</strong></label>
						<div class="col-sm-4">
							<input type="email" name="email" value="" maxlength="150"
								class="form-control bg-light text-dark" id="id_email"
								placeholder="Introduzca su correo electrónico">
						</div>
					</div>

					<div id="div_id_mensaje" class="form-group row">
						<label for="id_mensaje"
							class="col-sm-4 col-form-label requiredField"><strong>Mensaje</strong><span
								class="asteriskField">*</span></label>
						<div class="col-sm-4">
							<textarea name="mensaje" cols="40" rows="10" class="form-control bg-light text-dark"
								rrequired="" id="id_mensaje" placeholder="Ingrese su mensaje"></textarea> </div>
					</div>

					<div class="div.col align-self-center text-center">

						<button type="submit"
							class="btn btn-danger btn-sm font-weight-bold align-self-center text-center"
							style="border-radius: 40px;">Enviar</button>

					</div>
			</div>
		</div>
	</section>

</body>

</html>

{% endblock%}

kartMotos/templates/cuidadosPrevios.html
{% extends 'base.html' %}
{% block contenido %}
<script src="/static/js/alertas.js"></script>
<div class="container justify-content-center">
    <h1 class="text-center text-light pt-3 font-weight-bold">Cuidados previos antes de asistir a sus turnos</h1>
</div>

<div class="container bg-white d-flex justify-content-center mt-5 align-middle  align-items-center"
    style="width: 75%; border-radius: 25px;">
    <div class="container">
        <div class="row mt-5">
            <div class="col-3">
                <img src="/media/lavado-a-mano 1.png" alt="" srcset="" style="width: 150px; height: 150px;">
            </div>
            <div class="col-9">
                <h3 class="font-weight-bold">LAVARSE LAS MANOS FRECUENTEMENTE</h3>
                <p class="text-justify">Lávese las manos con frecuencia con agua y jabón por al menos 20 segundos,
                    especialmente después de haber estado en un lugar público, o después de sonarse la nariz, toser o
                    estornudar.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-3">
                <img src="/media/coronavirus 1.png" alt="" srcset="" style="width: 150px; height: 150px;">
            </div>
            <div class="col-9">
                <h3 class="font-weight-bold">CUBRIRSE LA BOCA Y NARIZ CON UNA MASCARILLA</h3>
                <p class="text-justify">El objetivo de la mascarilla es proteger a otras personas. Todos deben usar una
                    mascarilla en lugares públicos, pero solamente se pueden quitar con mucha precaución con los
                    cuidadoes previos necesarios.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-3">
                <img src="/media/distancia 1.png" alt="" srcset="" style="width: 150px; height: 150px;">
            </div>
            <div class="col-9">
                <h3 class="font-weight-bold">MANTENGA LA DISTANCIA Y EVITE EL CONTACTO DIRECTO</h3>
                <p class="text-justify">Mantenga la distancia minima de dos metros de las personas que no viven en su
                    casa hasta llegar al local.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-3">
                <img src="/media/caja-de-panuelos 1.png" alt="" srcset="" style="width: 150px; height: 150px;">
            </div>
            <div class="col-9">
                <h3 class="font-weight-bold">CUBRIRSE LA NARIZ Y LA BOCA AL TOSER Y ESTORNUDAR</h3>
                <p class="text-justify">Cúbrase siempre la boca y la nariz con un pañuelo desechable al toser o
                    estornudar o cúbrase con la parte interna del codo y no escupa. Recuerde descartar el pañulo en la
                    basura. Luego lávese las manos inmediatamente con agua y jabón.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-3">
                <img src="/media/rociar 1.png" alt="" srcset="" style="width: 150px; height: 150px;">
            </div>
            <div class="col-9">
                <h3 class="font-weight-bold">LIMPIE Y DESINFECTE</h3>
                <p class="text-justify">Limpie y desinfecte diaremente las superficies que se tocan con frecuencia. Esto
                    incluye las mesas, las manijas de las puertas, los interruptores de luz, los mesones, las barandas,
                    los escritorios, los lavamos y los lavaplatos.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-3">
                <img src="/media/620871 1.png" alt="" srcset="" style="width: 150px; height: 150px;">
            </div>
            <div class="col-9">
                <h3 class="font-weight-bold">MONITOREE SU SALUD A DIARIO</h3>
                <p class="text-justify">Esté atento a la aparición de síntomas como la tos, fibre, dificultad para
                    respirar u otros síntomas del COVID-19. Ante cualquier duda, consulte con su medico de cabecera o
                    con el centro de salud mas cercano.</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

kartMotos/templates/gracias.html
{% extends 'base.html' %}

{% block contenido %}
<h1>Mensaje enviado</h1><br>
<h3>Hemos recibido la información con su consulta. La responderemos a la brevedad.</h3>
{% endblock %}

kartMotos/templates/home.html
<!DOCTYPE html>
<html lang="es">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Turnos</title>
	<!-- Boostrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
		integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!-- Styles CSS -->
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<!-- Scripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<script src="https://kit.fontawesome.com/28abe86f4b.js" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
</head>

<body>
	<!-- NAVBAR -->
	<div class="container-fluid bg-light fixed-top border-white" style="border-style: none none solid none;">
		<div class="header row">
			<div class="col-4 d-flex justify-content-center">
				<a class="navbar-brand mt-2" href="{% url 'home' %}">AsociaciónKartingYMotos</a>
			</div>

			<div class="col-4 d-flex justify-content-center">
				<nav class="navbar navbar-expand-sm">
					<ul class="navbar-nav" style="font-size: 20px;">
						<li class="nav-item pl-5 pr-5"><a href="{% url 'nosotros' %}">Nosotros</a></li>
						<li class="nav-item pl-5 pr-5"><a href="{% url 'contacto' %}">Contacto</a></li>
						<!-- <li class="nav-item pl-5 pr-5"><a href="{% url 'cuidados' %}">Cuidados</a></li> -->
					</ul>
				</nav>
			</div>
			<!-- <div class="col-4 d-flex justify-content-center">
				<nav class="navbar navbar-expand-sm">
					<ul class="navbar-nav" style="font-size: 18px;">
						<li class="nav-item dropdown">
							<a class="nav-link bg-light text-dark pl-3 pr-3" href="#" id="navbardrop"
								data-toggle="dropdown" style="border-radius: 20px;">
								Invitado
							</a>
						</li>
					</ul>
				</nav>
			</div> -->
		</div>
	</div>


	<div class="container-fluid mt-5">
		<div class="container d-flex flex-column align-items-center justify-content-center pt-5">
			<h1 class="text-center text-white font-weight-bold" style="font-size: 50px;">Asociación de Karting Y Motos de Chaco</h1>
			<br>
			<h4 class="text-center">Plataforma oficial de inscripción</h4>
		</div>

		<div class="container d-flex flex-column pt-5" style="height:400px;">
			<div class="row">
				<div class="col-6 m-0 p-0">
					<img src="/media/imagen_karting.png" class="img-fluid w-100" alt="" srcset=""
						style="mix-blend-mode: luminosity; opacity: 0.8; z-index: -1; position: absolute; height: 300px;">
					<a href="{% url 'usuarios:registrar_usuario' %}" class="btn btn-danger btn-lg font-weight-bold position-absolute" style="top: 200px; left: 380px; border-radius: 25px;">Registrarse</a>
				<!-- 	<button type="button" class="btn btn-danger btn-lg font-weight-bold position-absolute"
						data-toggle="modal" data-target="#ModalRegistro"
						style="top: 200px; left: 380px; border-radius: 25px;">
						Registrarse
					</button> -->
				</div>
				<div class="col-6 m-0 p-0">
					<img src="/media/imagen_plan.png" class="img-fluid w-100" alt="" srcset=""
						style="mix-blend-mode: luminosity; opacity: 0.8; z-index:-1; position: absolute; height: 300px;">
					<a href="{% url 'login' %}" class="btn btn-light btn-lg font-weight-bold position-absolute"
						style="top: 200px; left: 20px; border-radius: 25px;">Iniciar sesión</a>
				</div>
			</div>
		</div>

		<!-- Modal Registro -->
		<!-- <div class="modal fade" id="ModalRegistro" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
			aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">¿Que tipo de usuario desea registrarse?</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body d-flex flex-column align-items-center justify-content-center">
						<div class="row mt-1">
							<a href="#"
								class="btn btn-danger btn-lg font-weight-bold align-self-center text-center"
								style="top: 200px; left: 20px; border-radius: 25px;">Registrarse como Cliente</a>
						</div>
						<div class="row mt-3 mb-2">
							<a href="#"
								class="btn btn-danger btn-lg font-weight-bold align-self-center text-center"
								style="top: 200px; left: 20px; border-radius: 25px;">Registrarse como Dueño</a>
						</div>
					</div>
				</div>
			</div>
		</div> -->


<!-- 		<div class="container d-flex flex-column align-items-center justify-content-center pt-5">
			<h2 class="text-center text-white font-weight-bold" style="font-size: 36px;">FUNCIONAMIENTO Y SERVICIOS</h2>
		</div>

		<div class="container-fluid pt-5">
			<div class="center-block">
				<div class="row">
					<div class="col align-self-center text-center">
						<img src="/media/Indumentaria.png" alt="" srcset="" style="height: 150px; width: 150px;">
						<h3 class="text-center text-white mt-2">INDUMENTARIA</h3>
					</div>
					<div class="col align-self-center text-center">
						<img src="/media/Peluquerias.png" alt="" srcset="" style="height: 150px; width: 150px;">
						<h3 class="text-center text-white mt-2">PELUQUERIAS</h3>
					</div>
					<div class="col align-self-center text-center">
						<img src="/media/Restaurante.png" alt="" srcset="" style="height: 150px; width: 150px;">
						<h3 class="text-center text-white mt-2">RESTAURANTES</h3>
					</div>
					<div class="col align-self-center text-center">
						<img src="/media/Bares.png" alt="" srcset="" style="height: 150px; width: 150px;">
						<h3 class="text-center text-white mt-2">BARES</h3>
					</div>
					<div class="col align-self-center text-center">
						<img src="/media/Gimnasio.png" alt="" srcset="" style="height: 150px; width: 150px;">
						<h3 class="text-center text-white mt-2">GIMNASIOS</h3>
					</div>
				</div>
			</div>

		</div>

		<div class="container d-flex flex-column align-items-center justify-content-center pt-5 mb-5 mt-5">
			<div class="row">
				<h4>El cliente entra a la web y puede tomar su turno en menos de 3 minutos.</h4>
			</div>
			<div class="row mt-5">
				<div class="col"><img src="/media/persona 1.png" alt="" srcset=""></div>
				<div class="col"><img src="/media/flechanegra 2.png" alt="" srcset=""></div>
				<div class="col"><img src="/media/Calendario.png" alt="" srcset=""></div>
				<div class="col"><img src="/media/flechanegra 2.png" alt="" srcset=""></div>
				<div class="col"><img src="/media/mujer 1.png" alt="" srcset=""></div>
			</div>
		</div>
	</div> -->
</body>

</html>

kartMotos/templates/homeSesion.html
{% extends 'base.html' %}

{% block contenido %}
<div class="container-fluid">
	<div class="container d-flex flex-column align-items-center justify-content-center pt-5">
		<h1 class="text-center text-white font-weight-bold" style="font-size: 50px;">AsociaciónKartingYMotos</h1>
		<br>
		<h4 class="text-center">Plataforma oficial de inscripción a las carreras de kartings y motos</h4>
	</div>

	<div class="container d-flex flex-column pt-5" style="height:400px;">
		<div class="row">
			<div class="col-6 m-0 p-0">
				<img src="/media/imagen_karting.png" class="img-fluid w-100" alt="" srcset=""
					style="mix-blend-mode: luminosity; opacity: 0.8; z-index: -1; position: absolute; height: 300px;">
				<a href="#"
					class="btn btn-danger btn-lg font-weight-bold position-absolute"
					style="top: 230px; left: 380px; border-radius: 25px;">Inscribir</a>
			</div>
			<div>	<a href="{% url 'carrera_karting:registrar_carrera' %}" class="btn btn-danger btn-lg font-weight-bold position-absolute"
				style="top: 450px; left: 420px; border-radius: 25px;">Registrar Carrera</a>
			</div>
			<div>	<a href="{% url 'pilotokart:registrar_piloto_kart' %}" class="btn btn-danger btn-lg font-weight-bold position-absolute"
					style="top: 450px; left: 700px; border-radius: 25px;">Registrar Piloto de Karting</a>
			</div>
			<div class="col-6 m-0 p-0">
				<img src="/media/imagen_plan.png" class="img-fluid w-100" alt="" srcset=""
					style="mix-blend-mode: luminosity; opacity: 0.8; z-index:-1; position: absolute; height: 300px;">
				<a href="{% url 'pilotokart:listar_piloto_kart' %}" class="btn btn-light btn-lg font-weight-bold position-absolute"
					style="top: 230px; left: 20px; border-radius: 25px;">Ver inscripciones</a>
			</div>
		
		</div>
	</div>
<!-- 	<div class="container d-flex flex-column pt-5" style="height:400px;">
		<div class="row">
			<div class="col-8 m-0 p-0">

				<div>	<a href="{% url 'pilotokart:registrar_piloto_kart' %}" class="btn btn-danger btn-lg font-weight-bold position-absolute"
					style="top: 100px; left: 20px; border-radius: 25px;">Registrar Piloto de Karting</a>
				</div>
				<div class="col-6 m-0 p-0">
					<img src="/media/imagen_plan.png" class="img-fluid w-100" alt="" srcset=""
						style="mix-blend-mode: luminosity; opacity: 0.8; z-index:-1; position: absolute; height: 300px;">
					<a href="{% url 'pilotokart:listar_piloto_kart' %}" class="btn btn-light btn-lg font-weight-bold position-absolute"
						style="top: 200px; left: 20px; border-radius: 25px;">Ver inscripciones</a>
	
				</div>
			</div>
		</div>	
	</div> -->

	<!-- <div class="container d-flex flex-column align-items-center justify-content-center pt-5">
		<h2 class="text-center text-white font-weight-bold" style="font-size: 36px;">FUNCIONAMIENTO Y SERVICIOS</h2>
	</div>

	<div class="container-fluid pt-5">
		<div class="center-block">
			<div class="row">
				<div class="col align-self-center text-center">
					<img src="/media/Indumentaria.png" alt="" srcset="" style="height: 150px; width: 150px;">
					<h3 class="text-center text-white mt-2">INDUMENTARIA</h3>
				</div>
				<div class="col align-self-center text-center">
					<img src="/media/Peluquerias.png" alt="" srcset="" style="height: 150px; width: 150px;">
					<h3 class="text-center text-white mt-2">PELUQUERIAS</h3>
				</div>
				<div class="col align-self-center text-center">
					<img src="/media/Restaurante.png" alt="" srcset="" style="height: 150px; width: 150px;">
					<h3 class="text-center text-white mt-2">RESTAURANTES</h3>
				</div>
				<div class="col align-self-center text-center">
					<img src="/media/Bares.png" alt="" srcset="" style="height: 150px; width: 150px;">
					<h3 class="text-center text-white mt-2">BARES</h3>
				</div>
				<div class="col align-self-center text-center">
					<img src="/media/Gimnasio.png" alt="" srcset="" style="height: 150px; width: 150px;">
					<h3 class="text-center text-white mt-2">GIMNASIOS</h3>
				</div>
			</div>
		</div>

	</div>

	<div class="container d-flex flex-column align-items-center justify-content-center pt-5 mb-5 mt-5">
		<div class="row">
			<h4>El cliente entra a la web y puede tomar su turno en menos de 3 minutos.</h4>
		</div>
		<div class="row mt-5">
			<div class="col"><img src="/media/persona 1.png" alt="" srcset=""></div>
			<div class="col"><img src="/media/flechanegra 2.png" alt="" srcset=""></div>
			<div class="col"><img src="/media/Calendario.png" alt="" srcset=""></div>
			<div class="col"><img src="/media/flechanegra 2.png" alt="" srcset=""></div>
			<div class="col"><img src="/media/mujer 1.png" alt="" srcset=""></div>
		</div>
	</div> -->
</div>

{% endblock %}